# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a44f7c4838f9e3341fefdbd0f80e641a86fb2f754bf192fbcff004d6436ad1f64c1384b3da382b346eb3027a3052c863ea77b86f51e4c7b7fa482d4cff61eb5

test:
  secret_key_base: 78ab01efcf4538f79795af4588f45938119a3fdb3ce64408527debae5b18d846944f2b478caf3fd0d32ea956f4a65c5baa4fed54179b2d94197f9dcdcb3f5678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
